[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["node scripts/setup.js"]

[start]
cmd = "node src/index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
